### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ghost** [loveorchids/sroie2019#1]
@loveorchids @firmamentqj Thank you for your hard work,

Can you upload a pretrained model so I can test.
Waiting for your reply

**Comment by whq-hqw** [comment]
Hi, as we did not spend much effort on OCR and Key Information Extraction tasks, only text detection model is available below. The result is expected to be around 94% in F1-score on SROIE test set:
```https://drive.google.com/open?id=1uZnBuLm_DLKwNukYhwbrbDxUmLa2XtPe```

Feel free to ask here if you meet any further problems.

**Comment by ghost** [comment]
Thanks,
Though how to use the pretrained model?

**Comment by whq-hqw** [comment]
First, make sure you installed the repo and prepared the data, test data should be placed under ```~/Pictures/dataset/ocr/SROIE2019_test``` by default).
Second, create a folder under ```~/Pictures/dataset/ocr``` called "_text_detection". 
Then place the pre-trained model under that folder and test with the data.

Feel free to ask here if you meet any further problems.

**Comment by ghost** [comment]
@loveorchids 
I copied [ this sample ](https://github.com/loveorchids/sroie2019/files/3677368/test.zip) to `SROIE2019_test`, the your `task1_epoch_0203.pth` to `_text_detection` folder, finally I ran `tb_test.py` and got error, have a look:

```
(sr) home@home-desktop:~/Documents/sroie2019/researches/ocr/textbox$ python tb_test.py
/home/home/Documents/sroie2019/omni_torch/utils/__init__.py:165: UserWarning: Cannot find models
  warnings.warn("Cannot find models")
Traceback (most recent call last):
  File "tb_test.py", line 278, in <module>
    test_rotation(opt)
  File "tb_test.py", line 140, in test_rotation
    if "module." + key not in weight_dict:
TypeError: argument of type 'SSD' is not iterable
```

**Comment by whq-hqw** [comment]
Please paste your command to run the tb_test.py. I would like to check if any argument was mistaken.
For example python3 tb_test.py -mpl XXXXXXX

**Comment by hamzaexe** [comment]
python C:/Users/35389/Documents/sroie2019/researches/ocr/textbox/tb_test.py --test_size 1000
C:/Users/35389/Documents/sroie2019\omni_torch\utils\__init__.py:165: UserWarning: Cannot find models
  warnings.warn("Cannot find models")
Traceback (most recent call last):
  File "C:/Users/35389/Documents/sroie2019/researches/ocr/textbox/tb_test.py", line 256, in <module>
    test_rotation(opt)
  File "C:/Users/35389/Documents/sroie2019/researches/ocr/textbox/tb_test.py", line 141, in test_rotation
    if "module." + key not in weight_dict:
TypeError: argument of type 'SSD' is not iterable

getting this error please help me
